name = "ConvolutionKernel"
uuid = "f2da46ed-aadf-4121-926c-31522e964e90"
authors = ["Michael Fiano <mail@mfiano.net> and contributors"]
version = "0.1.0"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
ConstructionBase = "187b0558-2788-49d3-abe0-74a17ed4e7c9"
Transducers = "28d57a85-8fef-5791-bfe6-a80928e7c999"

[compat]
Accessors = "0.1"
julia = "1.8"
